version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pixtag"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ijbyf0da4sea"
s3_prefix = "pixtag"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
